# Start a new data science project

Data Science Projects in RHOAI are used to organize users and AI-application related resources around a single shared space.

1. Make sure you are in the **Red Hat OpenShift AI Dashboard**. Remember that it can be accessed trough the OpenShift Web Console or directly on this URL: 

[source,bash]
----
    https://rhods-dashboard-redhat-ods-applications.apps.cluster-79242.dynamic.redhatworkshops.io/
----

[start=2]
1. Start by locating the **Data Science Projects** tab on the menu on the left.
2. Click the **Create project** button. A new window will pop-up.
3. There you can type your preferred project name. In my case, the **Name** will be `ai-edge-project`. Optionally, you can add a description.
4. Then, click **Create**. You will be redirected to the project dashboard page. With this, a new namespace called `ai-edge-project` will be created in your OpenShift node.

## Next section

Remember that we will use this data science project to deploy all the AI-resources tied to our model. Now it's time to create a workbench. That will be our platform for developing and testing the model.